// Tier 1 formation lookup table: curated get-ins (home -> formation) and get-outs
// (formation -> home), keyed by recognized FASR/formation name. Entries are
// auto-generated by the engine's search and verified (each get-out is confirmed to
// return to the squared set with identity restored). Because the search can't find
// a short closable path for every formation, the table is intentionally sparse and
// is meant to be supplemented with manually curated sequences.
//
// IMPORTANT caveat: a get-out is valid for the arrangement it was generated from.
// At use time the caller should verify it still closes the specific board (see
// closesHome), and fall back to the live search when it doesn't.
import { Sequencer } from 'dancing-squared-engine';
import type { Board } from 'dancing-squared-engine';

export interface FormationTable {
  getIns: Record<string, string[]>; // formation name -> sequence from home to that formation
  getOuts: Record<string, string[]>; // formation name -> sequence from that formation back home
}

/** Curated standard formations we want get-ins/get-outs for (home forms excluded). */
export const RECOGNIZED_FORMATIONS = [
  'Normal Lines',
  'Double Pass Thru',
  'Quarter Tag',
  'Tidal Line RH',
  'Tidal Wave RH',
  'Separated Columns',
  'Alamo Wave',
  'Eight Chain Thru',
  'Two-Faced Lines',
  'Ocean Waves RH',
];

// The exact home squared-set pose of each dancer id (from the engine's home set).
const HOME_POS: Record<number, { x: number; y: number; heading: number }> = {
  1: { x: 1, y: 3, heading: -Math.PI / 2 },
  2: { x: -1, y: 3, heading: -Math.PI / 2 },
  3: { x: 3, y: -1, heading: Math.PI },
  4: { x: 3, y: 1, heading: Math.PI },
  5: { x: -1, y: -3, heading: Math.PI / 2 },
  6: { x: 1, y: -3, heading: Math.PI / 2 },
  7: { x: -3, y: 1, heading: 0 },
  8: { x: -3, y: -1, heading: 0 },
};

/** Whether `board` is exactly back home (positions + facing within tolerance). */
export function isHome(board: Board): boolean {
  if (board.dancers.length !== 8) return false;
  for (const d of board.dancers) {
    const h = HOME_POS[d.id];
    if (!h) return false;
    if (Math.hypot(d.x - h.x, d.y - h.y) > 0.05) return false;
    let dh = Math.abs(d.heading - h.heading) % (2 * Math.PI);
    if (dh > Math.PI) dh = 2 * Math.PI - dh;
    if (dh > 0.05) return false;
  }
  return true;
}

/**
 * Build a formation table from the current available-call set. Mutates `seq`'s
 * state (resets it), so callers should pass a disposable sequencer.
 */
export function buildFormationTable(
  seq: Sequencer,
  opts: { getInMax?: number; getOutMax?: number; budget?: number } = {},
): FormationTable {
  const getInMax = opts.getInMax ?? 5;
  const getOutMax = opts.getOutMax ?? 7;
  const budget = opts.budget ?? 400;
  const getIns: Record<string, string[]> = {};
  const getOuts: Record<string, string[]> = {};

  for (const f of RECOGNIZED_FORMATIONS) {
    seq.reset();
    const getIn = seq.getout({ target: f, maxCalls: getInMax, budget });
    if (!getIn || !getIn.length) continue;
    // Verify the get-in actually reaches f, then find a get-out home. The getout
    // only returns a path when it reaches home (reachesTarget), so a found get-out
    // is known to close from the get-in's resulting arrangement. Use-time callers
    // should re-verify against the specific board (see closesHome).
    seq.reset();
    let ok = true;
    for (const c of getIn) if (!seq.apply(c).legal) { ok = false; break; }
    if (!ok || !seq.isAt(f)) continue;
    getIns[f] = getIn;
    const getOut = seq.getout({ target: 'Static Square', maxCalls: getOutMax, budget });
    if (getOut && getOut.length) getOuts[f] = getOut;
  }
  return { getIns, getOuts };
}

/**
 * Use-time check: does `path` take `board` (via `seq`, which doesn't mutate) back
 * to the squared set? The get-out search restores identity + sequence, so landing
 * on the squared set (geometric) means it closed home — matching the app's
 * "finish in square" definition. Callers use this to safely try a cached get-out
 * and fall back to the live search when it doesn't apply to the specific board.
 */
export function closesHome(
  seq: Sequencer,
  board: Board,
  path: string[],
): boolean {
  let cur = board;
  for (const c of path) {
    const r = seq.applyToBoard(cur, c);
    if (!r.legal) return false;
    cur = r.board;
  }
  return seq.isAt('Static Square', cur);
}
